services:
  - type: web
    name: telegram-mani-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_SECRET_TOKEN
        generateValue: true
      - key: WEBHOOK_URL
        sync: false
      - key: BACKEND_API_URL
        value: "https://project-mani-c0t3.onrender.com/api/chat"
